name: Scrape Kings League InfoJobs Website

on:
  workflow_dispatch:
    
  repository_dispatch:
    types:
      - webhook
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.24.3
          run_install: true
      - run: |
          node scraping/leaderboard.js
          git config --global user.name "jffc-dev-bot"
          git config --global user.email "jffc.dev@gmail.com"
          echo "https://$TOKEN:x-oauth-basic@github.com" > ~/.git-credentials
          git add -A
          git commit -m "bot(data): Get data from kings league"
          git push origin main
        env:
          TOKEN: ${{ secrets.CF_API_TOKEN }}
